#pragma once
#include <lvgl.h>

// Montserrat Medium with Latin Extended (ASCII 0x20-0x7E + Latin-1 Supplement 0xC0-0xFF).
// Covers Portuguese: ã á â à ç é ê í ó ô õ ú (and uppercase equivalents).
// Generated by tools/gen_fonts.sh — do not edit by hand.
extern const lv_font_t font_montserrat_lat_14;
extern const lv_font_t font_montserrat_lat_24;
extern const lv_font_t font_montserrat_lat_28;
extern const lv_font_t font_montserrat_lat_48;
